// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYB9Dc7QBkv1Hw3XjErJnia11Jj8IJd-c',
    appId: '1:567863769909:web:34bebbf65c728b11a6ea7c',
    messagingSenderId: '567863769909',
    projectId: 'projectfina-64c33',
    authDomain: 'projectfina-64c33.firebaseapp.com',
    storageBucket: 'projectfina-64c33.firebasestorage.app',
    measurementId: 'G-JHV7FGEJEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS5PXI0UlTadr7NZ_WgjW7S1C_xHLTV0k',
    appId: '1:567863769909:android:c02724bdee345ad4a6ea7c',
    messagingSenderId: '567863769909',
    projectId: 'projectfina-64c33',
    storageBucket: 'projectfina-64c33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJCz8c7SDa-NkS9CUdT8m8FlMFfPZu59w',
    appId: '1:567863769909:ios:fa2c4cfec8ee5b85a6ea7c',
    messagingSenderId: '567863769909',
    projectId: 'projectfina-64c33',
    storageBucket: 'projectfina-64c33.firebasestorage.app',
    iosBundleId: 'com.example.yumee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJCz8c7SDa-NkS9CUdT8m8FlMFfPZu59w',
    appId: '1:567863769909:ios:fa2c4cfec8ee5b85a6ea7c',
    messagingSenderId: '567863769909',
    projectId: 'projectfina-64c33',
    storageBucket: 'projectfina-64c33.firebasestorage.app',
    iosBundleId: 'com.example.yumee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYB9Dc7QBkv1Hw3XjErJnia11Jj8IJd-c',
    appId: '1:567863769909:web:65f1f04f3380e09ba6ea7c',
    messagingSenderId: '567863769909',
    projectId: 'projectfina-64c33',
    authDomain: 'projectfina-64c33.firebaseapp.com',
    storageBucket: 'projectfina-64c33.firebasestorage.app',
    measurementId: 'G-L6J15MG96M',
  );
}
